FROM @@nodeType:@@nodeEngine

ENV ENVIRONMENT=local
ENV NODE_ENV=development
ENV PORT=5000
ENV CONSOLE_LOGLEVEL=silly

ADD . /@@packageName/

EXPOSE ${PORT}

CMD cd /@@packageName && @@startCommand @@packageMain
